sudo: required

language: java

jdk:
  - openjdk8
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install: true

script:
  - |
    if [ "$TRAVIS_BRANCH" != "master" -o "$TRAVIS_PULL_REQUEST" == "true" ]; then
        ./mvnw -U verify jacoco:report coveralls:report -B
    fi
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then
        ./mvnw -U verify jacoco:report coveralls:report sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization=kazuki43zoo -Dsonar.projectKey=kazuki43zoo_mybatis-spring-boot-jpetstore -B
    fi
